export const START_FETCH_TEMPLATES = 'START_FETCH_TEMPLATES';
export const SET_TEMPLATES_LOADER = 'SET_TEMPLATES_LOADER';
export const SET_TEMPLATES = 'SET_TEMPLATES';

/**
 * delete item
 */

export const START_DELETE_TEMPLATE = 'START_DELETE_TEMPLATE';
export const SET_DELETE_TEMPLATE = 'SET_DELETE_TEMPLATE';
