/**
 * Sign in
 */
export const START_FETCH_USER_CREDENTIALS = 'START_FETCH_USER_CREDENTIALS';
export const SET_USER_CREDENTIALS = 'SET_USER_CREDENTIALS';
export const SET_USER_CREDENTIALS_LOADER = 'SET_USER_CREDENTIALS_LOADER';

/**
 * Sign out
 */
export const START_FETCH_LOGOUT = 'START_FETCH_LOGOUT';
export const CLEAR_USER_CREDENTIALS = 'CLEAR_USER_CREDENTIALS';
